FROM microsoft/dotnet:2.2-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV ASPNETCORE_ENVIRONMENT Development

COPY ./src/Voidwell.UserManagement.Api/*.csproj /tmp/

WORKDIR /tmp

RUN dotnet restore

WORKDIR /app/Voidwell.UserManagement.Api

EXPOSE 5000

CMD [ "dotnet", "watch", "run", "--no-launch-profile" ]